### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by boehmenkircher** [Woersty/LoxBerry-Plugin-Text2SIP#12]
When want to do a Call i get the following error:
/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_a99f.job.tsp: line 7: /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd: cannot execute binary file: Exec format error

**Comment by Woersty** [comment]
Dann muss das sipcmd binary neu kompiliert werden.
I guess in this case the sipcmd binary must be compiled on your system.

Siehe https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/6#issuecomment-263402609

**Comment by boehmenkircher** [comment]
OK, das hat geklappt, allerdings kommt jetzt das hier:

Starting sipcmd LoxBerry Text2SIP Plugin Edition v0.5 adapted by C.Woerstenfeld (C) 2017 git@loxberry.woerstenfeld.de 
Manager
Init
unknown option "-m"
please define a protocol to use!
Exiting.
~Manager
Tue Aug 15 10:27:24 2017 ## Deleting files

**Comment by Woersty** [comment]
Oh. Dachte das hätte ich schon veröffentlicht in github.
Leider ist mein Entwicklungssystem gestorben.
Muss ich erst schauen.
Dauert bis heute Abend fürchte ich.

**Comment by boehmenkircher** [comment]
Hallo, gibt es schon Neuigkeiten?

**Comment by Woersty** [comment]
Nein. Keine Zeit :(
Vielleicht am Wochenende noch.
Erst muss ich aber Fenster putzen usw....

**Comment by Woersty** [comment]
Ich habe mal die v0.7a kompiliert und ins GitHub geschoben.
https://github.com/Woersty/sipcmd und ins https://github.com/Woersty/LoxBerry-Plugin-Text2SIP   v0.7a gepackt.
Bei mir läuft es. Probier mal.

**Comment by boehmenkircher** [comment]
Ich bekomme beim Compile einen Fehler,.....
Ich nutze die Debian VM:

root@loxberry:/opt/loxberry/data/sipcmd-master# apt-get install libopal-dev libpt-dev wget unzip build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
libopal-dev is already the newest version.
libpt-dev is already the newest version.
unzip is already the newest version.
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@loxberry:/opt/loxberry/data/sipcmd-master# cd /opt/loxberry/data
root@loxberry:/opt/loxberry/data# rm master.zip
root@loxberry:/opt/loxberry/data# wget https://github.com/Woersty/sipcmd/archive/master.zip
--2017-09-04 08:40:54--  https://github.com/Woersty/sipcmd/archive/master.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Woersty/sipcmd/zip/master [following]
--2017-09-04 08:40:55--  https://codeload.github.com/Woersty/sipcmd/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 115161 (112K) [application/zip]
Saving to: âmaster.zipâ

master.zip                                                  100%[==========================================================================================================================================>] 112.46K   282KB/s   in 0.4s

2017-09-04 08:40:56 (282 KB/s) - âmaster.zipâ saved [115161/115161]

root@loxberry:/opt/loxberry/data# unzip master.zip
Archive:  master.zip
704aa1cca2c04a6ade8bb9b6eb044fc5b8cb1542
replace sipcmd-master/Makefile? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: sipcmd-master/Makefile
  inflating: sipcmd-master/README.md
   creating: sipcmd-master/bin/
   creating: sipcmd-master/bin/LoxBerry/
  inflating: sipcmd-master/bin/LoxBerry/sipcmd
  inflating: sipcmd-master/doc/README
  inflating: sipcmd-master/src/channels.cpp
  inflating: sipcmd-master/src/channels.h
  inflating: sipcmd-master/src/commands.cpp
  inflating: sipcmd-master/src/commands.h
  inflating: sipcmd-master/src/includes.h
  inflating: sipcmd-master/src/main.cpp
  inflating: sipcmd-master/src/main.h
  inflating: sipcmd-master/src/state.h
root@loxberry:/opt/loxberry/data# cd sipcmd-master
root@loxberry:/opt/loxberry/data/sipcmd-master# make clean; make
rm src/*.o sipcmd > /dev/null 2>&1
Makefile:23: recipe for target 'clean' failed
make: *** [clean] Error 1
g++ -c -Wall  src/main.cpp -o src/main.o -I/usr/include/opal -I/usr/include/ptlib -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/main.h:24,
                 from src/main.cpp:24:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type âunsigned intâ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^
g++ -c -Wall  src/commands.cpp -o src/commands.o -I/usr/include/opal -I/usr/include/ptlib -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/main.h:24,
                 from src/state.h:25,
                 from src/commands.cpp:29:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type âunsigned intâ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^
src/commands.cpp: In member function âvirtual bool Wait::ParseCommand(const char**, std::vector<Command*>&)â:
src/commands.cpp:452:30: warning: format â%uâ expects argument of type âunsigned int*â, but argument 3 has type âsize_t* {aka long unsigned int*}â [-Wformat=]
   sscanf(*cmds, "%u", &millis);
                              ^
g++ -c -Wall  src/channels.cpp -o src/channels.o -I/usr/include/opal -I/usr/include/ptlib -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/channels.h:25,
                 from src/channels.cpp:27:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type âunsigned intâ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^
g++ src/main.o src/commands.o src/channels.o -o sipcmd -lopal -lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible //usr/lib/libopal.so when searching for -lopal
/usr/bin/ld: cannot find -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible //usr/lib/libpt.so when searching for -lpt
/usr/bin/ld: cannot find -lpt
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'sipcmd' failed
make: *** [sipcmd] Error 1

**Comment by Woersty** [comment]
Geht es so?
```
cd /opt/loxberry/data/sipcmd-master
apt-get install g++-multilib
export CFLAGS='-m32'
export CXXFLAGS='-m32'
export LDFLAGS='-m32'
make
```

**Comment by boehmenkircher** [comment]
Leider nein,....

> root@loxberry:/opt/loxberry/data/sipcmd-master# make
g++ src/main.o src/commands.o src/channels.o -o sipcmd -lopal -lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible //usr/lib/libopal.so when searching for -lopal
/usr/bin/ld: cannot find -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible //usr/lib/libpt.so when searching for -lpt
/usr/bin/ld: cannot find -lpt
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'sipcmd' failed
make: *** [sipcmd] Error 1

**Comment by Woersty** [comment]
Mmmh 
Bin ich erst mal raus.
Habe die VM gerade nicht laufen.

**Comment by SHEVienna** [comment]
Ich habe leider auch das Problem. Kann es sein dass es ein Problem mit der  libopal-dev Version 3.10.10 gibt? Wie kann ich die Version wieder downgraden auf 3.10.2??
Bei mir lief alles sehr gut bis zum reboot der Maschine dann kam immer dieser Error:
/opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd: error while loading shared libraries: libopal.so.3.10.10: wrong ELF class: ELFCLASS32

Gibt es hier vielleicht schon eine Lösung ?

**Comment by TheSteiny** [comment]
> Ich habe leider auch das Problem. Kann es sein dass es ein Problem mit der libopal-dev Version 3.10.10 gibt? Wie kann ich die Version wieder downgraden auf 3.10.2??
Bei mir lief alles sehr gut bis zum reboot der Maschine dann kam immer dieser Error:
/opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd: error while loading shared libraries: libopal.so.3.10.10: wrong ELF class: ELFCLASS32

> Gibt es hier vielleicht schon eine Lösung ?

Ich gehe mal davon aus du hast das PlugIn in der VM laufen - also x86-64 Architektur - da hatte ich das Problem auch.
Ursache war bei mir das beim Start des PlugIns die installierten Libaries mit den ARM Versionen ersetzt werden.

Versuch mal folgendes:
`apt-get remove libopal-dev libpt-dev`
`apt-get install libopal-dev libpt-dev`
`rm /opt/loxberry/config/plugins/text2sip/modify.me`

**Comment by user2099** [comment]
Nachdem ich auf meiner Synology ein Update installiert habe und im Anschluss neu gestartet läuft die Text2SIP nicht mehr im Loxberry unter der VM. Zuvor hat es immer funktioniert, wenn ich den von Woersty #6 Comment verwendet habe. Jetzt leider nicht mehr (Meldung aus Log: cannot execute binary file: Exec format error).
Besteht das Problem generell "nur" bei VMs oder tritt das Problem auch auf, wenn ich mir ein Raspberry Pi 3 kaufe und das Ganze da drauf installiere.

**Comment by Woersty** [comment]
Keine Lösung für VM. Ich schreibe es in die Doku.

**Comment by BadHarry1986** [comment]
Gibt es eine Lösung für VM? Habe auch das oben genannte Problem und leider noch keine Lösung.

**Comment by Woersty** [comment]
Ich kenne keine.

**Comment by TheSteiny** [comment]
v0.7a läuft bei mir in der VM (vmware / loxberry 0.2.4) seit ~ 3 Monate problemlos.
Hatte zu beginn probleme mit falschen binaries (siehe Post 5.Feb)

Aktuelle Version auf basis loxberry 1.x hab ich noch nicht probiert bzw. sehe ich dzt. auch keine Notwendigkeit.
