### ISSUE TITLE
EndedBySecurityDenial

### ISSUE THREAD

**Issue by as63517** [Woersty/LoxBerry-Plugin-Text2SIP#13]
Hi Woersty,

bekomme folgende Fehler im Log:

TestPhone::Main: calling "**610" using gateway "192.168.20.1" at Sat Oct  7 11:18:33 2017

Setting up a call to: sip:**610@192.168.20.1
LocalEndpoint::MakeConnection
LocalEndpointCreateConnection
LocalConnection
OnIncomingConnection: token=L46d9b0f12
connection set up to sip:**610@192.168.20.1
OnReleased: reason: EndedBySecurityDenial
## Wait: waiting for 100ms ##
OnReleased: reason: EndedBySecurityDenial
OnClearedCall
Wait: wait done
## Voice audiofile=/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_W9NI_wav ##
PlaybackAudioFile
PlaybackAudioFile: state 3
## Wait: waiting for 5000ms ##
~LocalConnection
2017-10-07 11:18:36 [LOG] Show logfile

Ist ne FritzBox 7590 SW6.9
Irgendeine Idee ?

**Comment by Woersty** [comment]
Ja. Zugangsdaten falsch oder Username / PW mit Sonderzeichen

**Comment by as63517** [comment]
Bin ratlos.... hab ich jetzt schon 10x geprüft/geändert ;)

![image](https://user-images.githubusercontent.com/32591379/31307566-2847337a-ab67-11e7-98bd-dd1bc8871ff5.png)

![image](https://user-images.githubusercontent.com/32591379/31307568-3e85b0d0-ab67-11e7-9a49-e695deaaa679.png)

**Comment by Woersty** [comment]
Mal versucht keine Zahlen als PW zu verwenden?
Komisch ist es schon ...

**Comment by as63517** [comment]
ich glaub ich check das mal mit dem avm support... mein loxberry ist gerade unter 2 adressen im netzt erreichbar. einmal die feste und dann noch ne 2. per dhcp ??? glaub meine fritz hat ne meise ;) melde mich....

**Comment by as63517** [comment]
![image](https://user-images.githubusercontent.com/32591379/31308071-3d39639e-ab70-11e7-8fe5-d7ab1003f854.png)

**Comment by as63517** [comment]
strange....

**Comment by Woersty** [comment]
Das ist ein bekannter bug des Loxberry 
Siehe Forum

**Comment by as63517** [comment]
Zack. Problem gelöst ;)

Funzt prima....
