### ISSUE TITLE
Recompile

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-Text2SIP#17]
```
apt-get install libopal-dev libpt-dev
cd /opt/loxberry/
mkdir sipcmd
cd sipcmd
wget https://github.com/Woersty/sipcmd/archive/master.zip
unzip master.zip
cd sipcmd-master/
make 
apt-get purge libopal-dev libpt-dev
cp libopal.so.3.10.10 /usr/lib/
chmod 644 /usr/lib/libopal.so.3.10.10
cp libpt.so.2.10.11 /usr/lib/
chmod 644 /usr/lib/libpt.so.2.10.11
cp libspeexdsp.so.1 /usr/lib/
chmod 644 /usr/lib/libspeexdsp.so.1
cp libcapi20.so.3 /usr/lib/
chmod 644 /usr/lib/libcapi20.so.3
cp libodbc.so.2 /usr/lib/
chmod 644 /usr/lib/libodbc.so.2
cp libopal.so.3.10.10 /usr/lib/
chmod 644 /usr/lib/libopal.so.3.10.10
cp libpt.so.2.10.11 /usr/lib/
chmod 644 /usr/lib/libpt.so.2.10.11
cp libspeexdsp.so.1 /usr/lib/
chmod 644 /usr/lib/libspeexdsp.so.1
cp libcapi20.so.3 /usr/lib/
chmod 644 /usr/lib/libcapi20.so.3
cp libodbc.so.2 /usr/lib/
chmod 644 /usr/lib/libodbc.so.2

```

**Comment by Woersty** [comment]
Siehe auch https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/12

**Comment by 19kirk79** [comment]
root@loxberry:/opt/loxberry/sipcmd/sipcmd-master# make
g++ -c -Wall  src/main.cpp -o src/main.o -I/usr/include/opal -I/usr/include/ptli           b -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/main.h:24,
                 from src/main.cpp:24:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type            ‘unsigned int’ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^~~~
g++ -c -Wall  src/commands.cpp -o src/commands.o -I/usr/include/opal -I/usr/incl           ude/ptlib -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/main.h:24,
                 from src/state.h:25,
                 from src/commands.cpp:29:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type            ‘unsigned int’ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^~~~
src/commands.cpp: In member function ‘virtual bool Wait::ParseCommand(const char           **, std::vector<Command*>&)’:
src/commands.cpp:452:30: warning: format ‘%u’ expects argument of type ‘unsigned            int*’, but argument 3 has type ‘size_t* {aka long unsigned int*}’ [-Wformat=]
   sscanf(*cmds, "%u", &millis);
                              ^
g++ -c -Wall  src/channels.cpp -o src/channels.o -I/usr/include/opal -I/usr/incl           ude/ptlib -Isrc/
In file included from /usr/include/opal/h323/h323.h:39:0,
                 from src/includes.h:25,
                 from src/channels.h:25,
                 from src/channels.cpp:27:
/usr/include/opal/h323/h323ep.h:148:30: warning: converting to non-pointer type            ‘unsigned int’ from NULL [-Wconversion-null]
       unsigned int options = NULL,      ///<  options to pass to conneciton
                              ^~~~
g++ src/main.o src/commands.o src/channels.o -o sipcmd -lopal -lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/../../../../l           ib/libopal.so when searching for -lopal
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libopal.so when searching for            -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/../../../libo           pal.so when searching for -lopal
/usr/bin/ld: skipping incompatible //usr/lib/libopal.so when searching for -lopa           l
/usr/bin/ld: cannot find -lopal
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/../../../../l           ib/libpt.so when searching for -lpt
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libpt.so when searching for -           lpt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/../../../libp           t.so when searching for -lpt
/usr/bin/ld: skipping incompatible //usr/lib/libpt.so when searching for -lpt
/usr/bin/ld: cannot find -lpt
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'sipcmd' failed
make: *** [sipcmd] Error 1

**Comment by Woersty** [comment]
Also bei mir geht es.
Wenn ich es auf einem LoxBerry auf Raspberry oder unter Hyper-V so mache geht es: https://www.loxwiki.eu/display/LOXBERRY/Text2SIP#Text2SIP-BekannteProbleme

[sipcmd_x86-64.zip](https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/files/2301136/sipcmd_x86-64.zip)

```
root@webserver:/opt/loxberry/sipcmd/sipcmd-master# file sipcmd
sipcmd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5eea0ff29393a6ccf52f414749809a5aa4ff9335, not stripped
root@webserver:/opt/loxberry/sipcmd/sipcmd-master# ./sipcmd
Starting sipcmd LoxBerry Text2SIP Plugin Edition v0.7a adapted by C.Woerstenfeld (sipcmd developed by Tuomo Makkonen)
Manager
Init
please define a protocol to use!
Exiting.
~Manager
```
