### ISSUE TITLE
loxberry beyond limits

### ISSUE THREAD

**Issue by joerglox** [Woersty/LoxBerry-Plugin-Text2SIP#18]
Hallo,
habe heute meinen Loxberry auf die neue Version geupdated.
Nach installation der TEXT2SIP und anlegen der Ansage bekomme ich folgende Fehlermeldung:

sh: 1: cannot create /opt/loxberry/log/plugins/text2sip/Text2SIP.log: Permission denied sh: 1: cannot create /opt/loxberry/log/plugins/text2sip/Text2SIP.log: Permission denied 
Fehler beim Einfügen des Anrufs in die Warteschlange.

http://LoxBerry/plugins/text2sip/?mode=make_call&vg=1 ergibt :o)

habe auch schon alle mit apt-get update und apt-get upgrade probiert.

https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/6#issuecomment-263402609
das hab ich auch schon durch.
Funktioniert leider alles nicht.

Vielen Dank für die Hilfe schonmal vorab.

Grüße
Jörg

**Comment by Woersty** [comment]
Also bei mir funktioniert es mit https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/archive/v2018.3.14.zip
Stell mal auf Debug um und speichere und dann Teste.

**Comment by Woersty** [comment]
Achso - musst auf **Nur benachrichtigen** stellen in der Plugin-Verwaltung. Und dann **Auf neue Updates prüfen** anklicken

**Comment by Woersty** [comment]
Geht die Version v2018.3.15 bei dir?

**Comment by joerglox** [comment]
Hey, passt! Alles funktioniert! Vielen Dank!
