### ISSUE TITLE
Port-Weiterleitung

### ISSUE THREAD

**Issue by pawy** [Woersty/LoxBerry-Plugin-Text2SIP#19]
Hi

Was ist genau der Unterschied ob ich den Anruf via Web-Konfiguration triggere (was funktioniert) oder via GET, was zu folgendem Fehler führt:

2018-03-13 22:57:23 Anfrage zum Abspielen von Ansage #1
2018-03-13 22:57:24 ERROR0005: Kann mich auf Port 5060 nicht zum SIP-Proxy verbinden. (free4.voipgateway.org)

Der Proxy ist im Internet von sipcall.ch. Also keine lokale FritzBox oder sowas.
Port Weiterleitung 5060 zu meinem Loxberry hilft auch nicht.

Kannst du mir helfen?

**Comment by Woersty** [comment]
Das eine geht über Perl und das andere über PHP.
Dann wird über PHP wohl was nicht korrekt übergeben?

**Comment by Woersty** [comment]
Bitte mal die aktuelle Pre-Release Version installieren - musst auf **Nur benachrichtigen** stellen in der Plugin-Verwaltung. Und dann **Auf neue Updates prüfen** anklicken.
Stell dann mal auf Debug um und speichere und dann Teste.

**Comment by pawy** [comment]
Danke für die Antwort
Gleiches verhalten, ausser dass es jetzt einen Logfile-Viewer gibt :)
Hilft dir das Log weiter vom erfolgreichen Testanruf?

**Comment by Woersty** [comment]
Mail mal beide. loxberry ät loxberry.woerstenfeld.de

**Comment by pawy** [comment]
Also wenn ich den Block im index.php auskommentiere in welchem du die Verbindung zum Proxy auf Port 5060 testest, dann funktionierts.

`system ('echo | nc -w 1 "'.$SIPCMD_SIP_PROXY.'" 5060',$code);
    if ( $code == 0 )
    {
      debug('DBG_OK_CONNECT_PROXY'," Proxy: $SIPCMD_SIP_PROXY",5);
    }
    else
    {
      error_log( date('Y-m-d H:i:s ').$plugin_phrase_array['ERROR0005']." ($SIPCMD_SIP_PROXY)\n", 3, $pluginlogfile);
      die($plugin_phrase_array['ERROR0005']." ($SIPCMD_SIP_PROXY)");
    }`

Da wird, soweit ich das sehe nur die Verbindung zum Proxy aufgebaut und nach 1s wieder geschlossen (sprich getestet).

**Comment by Woersty** [comment]
Probier mal Version v2018.3.15 da hab ich das netcat rausgenommen. Ist eigentlich nicht nötig
