### ISSUE TITLE
Geht nicht :-)

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-Text2SIP#2]
![20-11-2016 13-05-21](https://cloud.githubusercontent.com/assets/16830799/20462595/5a48676e-af22-11e6-977d-1f8828ac8dd3.png)
Hier das Log von einer Fritzbox - Anruf wird nicht abgesetzt:

Add job for guide 1 to queue as #2
################################ Start job from /opt/loxberry/data/plugins/text2sip/wav/Text2SIP_H1zP.job.tsp @ Sun Nov 20 12:56:54 2016 
Sun Nov 20 12:56:54 2016 ## Generating voice 
Sun Nov 20 12:56:54 2016 ## Converting voice 
Sun Nov 20 12:56:54 2016 ## Calling xxxxxxxxx
Starting LoxBerry Plugin Edition v0.2 by C.Woerstenfeld (C) 2016 git@loxberry.woerstenfeld.de 
Manager
Init
initialising SIP endpoint...
Listening for SIP signalling on 0.0.0.0:TestChanAudio
TestChanAudio
5060
SIP listener up
registered as sip:620@fritz.box
Created LocalEndPoint
Main
DIAL_TIMEOUT is 1
## Call ##
TestPhone::Main: calling "xxxxxxxxxxxx" using gateway "fritz.box" at Sun Nov 20 12:56:55 2016

Setting up a call to: sip:xxxxxxx@fritz.box
LocalEndpoint::MakeConnection
LocalEndpointCreateConnection
LocalConnection
OnIncomingConnection: token=L20aeec832
connection set up to sip:xxxxxx@fritz.box
Problem running command sequence ("cxxxxxxxx;w100;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_kgOu.wav;w5000;h"):
  Call: Dial timed out, check -T / --dialtimeout command line option
TestPhone::Main: shutting down
OnReleased: reason: EndedByLocalUser
OnReleased: reason: EndedByLocalUser
OnClearedCall
~LocalConnection
TestPhone::Main: exiting...
Exiting.
~Manager
2016-11-20 12:57:03 [LOG] Show logfile
Sun Nov 20 12:56:54 2016 ## Deleting files 
################################ End job from /opt/loxberry/data/plugins/text2sip/wav/Text2SIP_H1zP.job.tsp 
2016-11-20 13:00:20 [LOG] Show logfile`

**Comment by Woersty** [comment]
Na 1 Sekunde maximale Rufdauer ist auch echt wenig. Findest du nicht? Probier mal 60 Sekunden.
Da hat das Netz das Handy ja noch nicht mal lokalisiert.

**Comment by mschlenstedt** [comment]
Arrrgh, ich hatte einfach blind Deine Defaultwerte übernommen, ohne mir groß Gedanken zu machen. Habe jetzt den Wert auf 120s genommen - es geht! Genial!

**Comment by Woersty** [comment]
Setze den Default auf 60.

**Comment by mschlenstedt** [comment]
Damit ist der Loxone Callerservice obsolete 👍
