### ISSUE TITLE
Pluginsprache en fehlt

### ISSUE THREAD

**Issue by christianTF** [Woersty/LoxBerry-Plugin-Text2SIP#21]
... und kein Fallback auf de

https://www.loxforum.com/forum/projektforen/loxberry/plugins/162409-text2sip-fehler-beim-aufruf-nach-installation#post162414

**Comment by Woersty** [comment]
To Do... Kommt mit dem Komplettumbau auf Schnittstelle 2.0 und Multilanguage. 
Irgendwann...

**Comment by Woersty** [comment]
Will have a look soon....

**Comment by Woersty** [comment]
See also https://www.loxforum.com/forum/projektforen/loxberry/plugins/193506-text2sip-fehlerhafte-weboberfläche?p=195839#post195839
