### ISSUE TITLE
Text2SIP für Mobilnummer am Vodafone-Kabelanschluß

### ISSUE THREAD

**Issue by Datenkrake156** [Woersty/LoxBerry-Plugin-Text2SIP#24]
Hallo,
habe mir als Vorbereitung für eine Loxone-Installation als Einstieg mal diese App (V2018.3.15) installiert und bin fast verrückt geworden (bin Kaufmann und Rentner, kein Programmierer).
Konfiguration der App genau nach Anweisung noch ohne MS, nach einigem Hin und Her erschien grün Meldung von einer Warteschleife, aber in der Fritz-Box wurde kein ausgehender Anruf angezeigt und der Klugschwatz klingelte auch nicht.
Test mit Anruf auf andere Festnetznummer war erfolgreich.
Einen ganzen Tag lang nach dem Fehler gesucht: Wegen der unverschämten Preise von Vodaschreck für einen Mobilanruf nutze ich einen anderen SIP-Anbieter (Nexxt Mobile) für Anrufe auf Mobil- und Auslandsnummern und habe dies in den Wahlregeln der Fritz-Box fest hinterlegt. Daher kommt nach der Nummernwahl erst eine Ansage mit dem Minutenpreis für diesen Anruf und dann wird durchgewählt. Damit wird der Defaultwert Pause vor Ansage ausgehebelt. Habe diesen Wert auf 5000 ms hochgesetzt und Erfolg! Jetzt kommt die Meldung auch durch. Vielleicht könnt Ihr diese Erfahrung ja in den FAQs einbauen.

ZS: feine App, gefällt mir! Erster Einstz wird eine Warnmeldung auf den Klugschwatz für den Wassersensor sein. Weiter so.

**Comment by Woersty** [comment]
Danke mach ich bei Gelegenheit.

**Comment by Woersty** [comment]
https://www.loxwiki.eu/display/LOXBERRY/Text2SIP#Text2SIP-SonderfallNexxtMobile
