### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by aefirefly** [Woersty/LoxBerry-Plugin-Text2SIP#26]
Arbeite mit einer Fritzbox. Alles eingestellt und eingegeben wie beschrieben.
Möchte ich zum Testen im Plugin direkt auf das "Telefon" Symbol drücken erscheint diese Fehlermeldung.

Log ist natürlich leer :-)

sh: 1: cannot create /opt/loxberry/log/plugins/text2sip/Text2SIP.log: Permission denied sh: 1: cannot create /opt/loxberry/log/plugins/text2sip/Text2SIP.log: Permission denied 
Fehler beim Einfügen des Anrufs in die Warteschlange

**Comment by Woersty** [comment]
Gelöst ab Text2SIP v2019.02.12
