### ISSUE TITLE
Ansage spielt schon bei 183 Progress und nicht erst bei 200 OK, daher beim Abheben keine Ansage oder nur noch der Rest 

### ISSUE THREAD

**Issue by hismastersvoice** [Woersty/LoxBerry-Plugin-Text2SIP#5]
Interne Rufe gehen ohne Probleme, Text wird abgespielt MFV kann verwendet werden.
Wird aber eine externe Nummer verwendet, egal ob Festnetz oder Mobil, klingelt es zwar, wird aber wenn ich annehme direkt ohne Wiedergabe wieder aufgelegt.

**Comment by Woersty** [comment]
Könnte ein Codec Problem sein. Ohne SIP Capture kann ich dazu leider nicht viel sagen.
Was steht denn im Log (Debug Level)?
Ansonsten mal als root: `tcpump -s0 -w /opt/loxberry/data/capture.pcap` ausführen und mir die capture.pcap mailen. Bitte nicht hier anhängen, da stehen deine Daten drin!
Beenden des Captures mit Strg+c 

Gruß

**Comment by hismastersvoice** [comment]
Log
http://music-server.net/log.txt
http://music-server.net/capture.pccd

**Comment by Woersty** [comment]
Also auf Anhieb sehe ich das Problem nicht.
[Audio.zip](https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/files/611595/Audio.zip)
Allerdings scheint er die Ansage schon beim 183 PROGRESS abzuspielen.
Nicht erst beim 200 OK. 
Hast du mal einen Festanschluss probiert? 
Oder probier mal eine ganz lange Ansage, ob du den Rest hörst...  

Ich denke das ist ein Handy-Netz-Problem.  (Early media)
Mal sehen ob ich eine Lösung finde.

**Comment by hismastersvoice** [comment]
Ist sowohl im Festnetz als auch Mobil.
Könnte sein das er die Nachricht zu früh abspielt und wenn ich annehme ja dann schon fertig ist.

**Comment by Woersty** [comment]
Sag ich ja. Er spielt es schon beim Progess ab. Daher solltest du ja mal eine längere probieren, ob das geht.

**Comment by hismastersvoice** [comment]
Auch bei 2 und 3 Mal so langen Texten bleibt es so.

**Comment by Woersty** [comment]
Tausch mal die Datei /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd in gegen diese hier aus (entpackt) und schick mir das Log, bitte.
[sipcmd.zip](https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/files/612156/sipcmd.zip)
Ich denke, dass ich an dem Verhalten so leicht nichts ändern kann.
Wenn ich mein Handy ausschalte und die Ansage vom Provider kommt, 
habe ich ein ähnliches Verhalten. Leider unterscheidet das Tool nicht zwischen Connect und Progress.
In beiden Fällen kommt eine 2 als Status.

**Comment by hismastersvoice** [comment]
http://music-server.net/log2.txt

**Comment by hismastersvoice** [comment]
Wenn ich den Text 4x wiederholen lasse, dann höre ich eine Ansage der 4.
(Smarthome-Alarm: Der Rauchmelder im Schlafzimmer hat ausgelöst. Smarthome-Alarm: Der Rauchmelder im Schlafzimmer hat ausgelöst. Smarthome-Alarm: Der Rauchmelder im Schlafzimmer hat ausgelöst. Smarthome-Alarm: Der Rauchmelder im Schlafzimmer hat ausgelöst.)
Denke mal wenn ich aber nicht gleich dran gehen höre ich wieder nichts.

**Comment by Woersty** [comment]
Das deckt sich mit meiner Vermutung. Da er schon die Ansagen ab dem Moment spielt in dem er das Progress erhält. Komisch nur, dass auch ein Progress beim Festnetz kommt. Welchen Provider hast du? Nicht Telekom, oder? Da sipcmd nicht unterscheidet, kann ich vorerst nichts dagegen tun.
Ich versuche aber später eine Lösung zu finden und lasse das hier mal offen.

**Comment by hismastersvoice** [comment]
KabelBW...

**Comment by Woersty** [comment]
Dachte ich mir. Melde mich hier, wenn ich eine Idee habe.
Momentan fehlt mir die Zeit, die ganzen Opal und sipcmd sourcen zu durchwühlen.
Außerdem habe ich keine Ahnung von C++ und quäle mich da sehr mit....

**Comment by hismastersvoice** [comment]
Ist ja nicht ganz so wichtig... Vorerst ist es ja wichtig das es intern sauber läuft... und das tut es.

**Comment by Woersty** [comment]
Bin zu blöd, das zu lösen. :o(
Also falls jemand den sipcmd Code versteht, kann er da gern helfen...
Das es aber ein Problem vom sipcmd ist https://github.com/Woersty/sipcmd schließe ich das hier.
