### ISSUE TITLE
Problem mit Wartezeit für Bestätigungscode

### ISSUE THREAD

**Issue by Blaubart** [Woersty/LoxBerry-Plugin-Text2SIP#6]
Bei mir funktioniert soweit alles. Auch das Anrufen auf ein Handy klappt sehr gut. Nur die Wartezeit für den Bestätigungscode scheint nicht immer berücksichtigt zu werden. Unmittelbar nach der Ansage wird bei manchen Ansagen aufgelegt. Im Logfile steht dazu folgendes:

```
PlaybackAudioFile
PlaybackAudioFile: opening file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_YWNZ.wav" as WAV
PlaybackAudio
TestChanAudio::FillPlaybackBuffer: I/O error
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 0
Problem running command sequence ("c+49151xxxxxxxx;w1000;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_YWNZ.wav;w50000;h"):
  Voice: error reading file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_YWNZ.wav"
TestPhone::Main: shutting down
```

Bei anderen klappt es:
```
PlaybackAudioFile
PlaybackAudioFile: opening file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_UctU.wav" as WAV
PlaybackAudio
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 1
## Wait: waiting for 5000ms ##
Wait: wait done
## Hangup ##
```

**Comment by Woersty** [comment]
Kann gerade nicht testen. 
`TestChanAudio::FillPlaybackBuffer: I/O error`
`Voice: error reading file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_YWNZ.wav"`
Faktisch hat er im oberen Beispiel die Ansage nicht lesen können.
Hast du mal 0151 statt +49151 versucht?
Macht das einen Unterschied? Habe das nie mit +49 probiert.

**Comment by Blaubart** [comment]
Hab ich, macht keinen Unterschied.
Aber die Ansage wird vorgelesen. Also muss er sie auch lesen können, oder?
Ich vermute, es hat war mit Änderungen der Ansage zu tun, die nicht korrekt übernommen werden. Ich habe z.B. gerade einen Text verlängert. Vorher war die Wartezeit von 5s hier vorhanden, anschließend nicht mehr.

**Comment by Woersty** [comment]
Wie hast du das aufgerufen? 
Über den Hörer im Kreis?
Da wird gar nix übernommen - er übergibt dann die Werte auf der AdminWebseite 1:1.
Auch wenn man nicht Konfiguration speichern klickt.

Wie auch immer - wenn er `I/O error` und `error reading file` schreibt, wird es wohl so sein?
Ist die SD-Karte vielleicht mackig? Wäre nicht der erste Raspberry bei dem das passiert.

Ansonsten könntest du in der `index.cgi` unter `/opt/loxberry/webfrontend/cgi/` die Zeilen 272 & 273 auskommentieren (# davor) 
```
    $cmd = 'rm -f '.$pluginjobfile.' '.$plugintmpfile.' '.$pluginwavfile.' 2>&1 >>'.$pluginlogfile;
    system ("echo '".$cmd."' >> $pluginjobfile");
```
Dann löscht er die Dateien nach Ausführen des Jobs nicht und du kannst händisch mit den Dateien in `/opt/loxberry/data/plugins/text2sip` testen.

Einfach die `Text2SIP_xxxx.job.tsp` Datei öffnen und die Zeile mit **sipcmd** rauskopieren und auf der Shell ausführen.

Gruß

**Comment by Blaubart** [comment]
> Wie hast du das aufgerufen?
Über den Hörer im Kreis?
Da wird gar nix übernommen - er übergibt dann die Werte auf der AdminWebseite 1:1.
Auch wenn man nicht Konfiguration speichern klickt.

Ja, ich habe mit dem Hörersymbol aufgerufen. Wenn die dort eingestellten Werte übernommen werden, dann sollten die 5s Wartezeit ja auch übernommen werden, oder?
Die SD-Karte schließe ich eher aus. Habe sonst keine Fehlermeldungen, außer mit dem Backup-Plugin von dir, das hab ich in dem dazugehörigen Repository schon mal geschrieben.

Die restlichen Tips von dir werde ich mal testen.

Danke!!

**Comment by Blaubart** [comment]
Hallo,

ich habe deine Tips mal ausprobiert. Ich habe die beiden Zeilen heraus kommentiert und die Ansagen mit dem grünen Hörersymbol senden lassen. Bei einer tritt immer wieder das Problem auf, dass sofort nach der Ansage aufgelegt wird.
Starte ich die Ansage mit der Zeile mit sipcmd, ist es ganz das gleiche. Hier noch die Meldungen, die bei der Ansage ohne Wartezeit erscheint:
```
## Voice audiofile=/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_zgh3.wav ##
PlaybackAudioFile
PlaybackAudioFile: opening file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_zgh3.wav" as WAV
PlaybackAudio
TestChanAudio::FillPlaybackBuffer: I/O error
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 0
Problem running command sequence ("c**620;w1000;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_zgh3.wav;w20000;h"):
  Voice: error reading file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_zgh3.wav"
TestPhone::Main: shutting down
```

Eine Ansage inkl. der Wartezeit liefert:
```
## Voice audiofile=/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_3HRs.wav ##
PlaybackAudioFile
PlaybackAudioFile: opening file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_3HRs.wav" as WAV
PlaybackAudio
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 1
## Wait: waiting for 20000ms ##
```

**Comment by Woersty** [comment]
Leider habe ich momentan keine Ahnung warum sporadisch ein `TestChanAudio::FillPlaybackBuffer: I/O error` kommt.
Bin auch kein C++ Experte.
Hast du alle Pakete aktuell auf dem Loxberry?
Könntest den sipcmd ja mal bei dir auf dem System kompilieren.
Aber das wäre dann etwas Aufwand... Soll ich dir sagen, wie?

**Comment by Blaubart** [comment]
OK, trotzdem schon mal Danke. Ich poste es mal im Forum, vielleicht kann jemand helfen. 
Hast du vielleicht außerdem noch einen Tip für mich, warum das Backup-Plugin bei mir nicht funktioniert?

**Comment by Woersty** [comment]
Vorher mach lieber ein Backup der SD Karte damit du wieder zurück kannst zum Ursprung.
Die Installation frisst fast 300 MB .... 
Also:
Als `loxberry `anmelden und zu `root `ummelden
```
apt-get install libopal-dev libpt-dev wget unzip build-essential
cd /opt/loxberry/data
wget https://github.com/Woersty/sipcmd/archive/master.zip
unzip master.zip
cd sipcmd-master
make clean; make
```

Dann die Datei sipcmd aus dem Verzeichnis nach /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/ kopieren:
`cp /opt/loxberry/data/sipcmd-master/sipcmd /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/`
und Rechte anpassen: 
`chown loxberry:loxberry /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd`
und
`chmod 755 /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd`

Viel Glück!

Zum Backup habe ich noch keine Idee. Schau ich demnächst mal.

**Comment by Blaubart** [comment]
Das funktioniert. Was hab ich jetzt mit der Installation geändert?
Eins ist mir noch aufgefallen. Wenn man den Bestätigungscode gedrückt hat, sollte  aufgelegt werden. Das wäre recht praktisch.

**Comment by Woersty** [comment]
Naja, kann ja sein, dass man mehrere Ziffern eingeben will...
Ich denk drüber nach. Könnte man als Checkbox machen.

Du hast sipcmd für exakt dein System ne kompiliert.
Welche Version benutzt du denn? Das 0.2.2 image + Update auf 0.2.3?
Hast du alle Pakete aktuell? (  `apt-get update ; apt-get upgrade` )

**Comment by Blaubart** [comment]
stimmt. Checkbox wäre da die beste Option. Oder vielleicht ein Feld: "Anruf beenden, wenn folgender Bestätigungscode eingegeben wurde"
Ich nutze 0.2.3 und apt-get update ; apt-get upgrade hab ich noch nicht gemacht. Das mach ich heute Abend mal.

Danke für deine Arbeit und deine Hilfe!!

**Comment by Woersty** [comment]
Problem mit der Wartezeit ist ab 0.4 gelöst. Lag am . im Dateinamen.
