### ISSUE TITLE
Text2SIP spricht nicht mit mir

### ISSUE THREAD

**Issue by bla1bla1** [Woersty/LoxBerry-Plugin-Text2SIP#7]
Hallo,

ich habe das Plugin auf einem frisch aufgesetzten Loxberry installiert und getestet.
Ich werde zwar angerufen (getestet auf einem internen Telefon sowie auf einem Handy), jedoch höre ich keinen Text o.Ä.

Ich verwende hierfür eine FritzBox 7490, die wie in der Anleitung beschrieben konfiguriert wurde.
Zudem habe ich deine modifizierte "sipcmd" aus einem anderen Issue getestet, leider mit dem selben Ergebnis.

Die generierten wav-Files (tmp und konvertiert) habe ich mal spaßeshalber via SCP auf meine Windows-Kiste gezogen. Die wurden korrekt erstellt und der Text ist als Audio vorhanden.

Anbei die Ausgabe einer manuellen Ausführung der sipcmd.

[text2sip.log.txt](https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/files/614764/text2sip.log.txt)
[text2sip.debug.txt](https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/files/614767/text2sip.debug.txt)

Danke für die Unterstützung und für dieses Plugin.
Daniel

**Comment by Woersty** [comment]
Geht es auch dann nicht, wenn du den Anruf über das Hörersymbol auf der Plugin-Adminseite auslöst?

**Comment by bla1bla1** [comment]
Nein, auch dann leider nicht.
Diesmal konnte ich im Log jedoch einen Fehler erkennen:

```
PlaybackAudio
TestChanAudio::FillPlaybackBuffer: I/O error
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 0
Problem running command sequence ("cMEINE_TEL_NUMMER;w500;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_dVZJ.wav;w5000;h"):
  Voice: error reading file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_dVZJ.wav"
TestPhone::Main: shutting down
OnClosedMediaStream
```

Die Datei "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_dVZJ.wav" war jedoch zum Zeitpunkt des Anrufs vorhanden.

**Comment by bla1bla1** [comment]
Mit der originalen Version von sipcmd kommt der Fehler nicht mehr, jedoch auch keine Sprachausgabe am Telefon.

Hier das entsprechende Log:
```
OnEstablished
## Wait: waiting for 500ms ##
OnEstablished
OnEstablishedCall
In call with sip:BLABLABLA using local:loxberry token=[Cdf7561ef1]
Wait: wait done
## Voice audiofile=/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_AQ_1.wav ##
PlaybackAudioFile
PlaybackAudioFile: opening file "/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_AQ_1.wav" as WAV
PlaybackAudio
StopAudioPlayback
TestChanAudio::PlaybackAudio: play back done 1
```

Und so sah das Verzeichnis während des Jobs aus:

```
total 164
drwx------ 2 loxberry loxberry  4096 Nov 27 23:37 .
drwxr-xr-x 3 loxberry loxberry  4096 Nov 27 14:09 ..
-rw-r--r-- 1 loxberry loxberry 49772 Nov 27 23:37 Text2SIP_AQ_1.wav
-rw-r--r-- 1 loxberry loxberry 99500 Nov 27 23:37 Text2SIP_tSBz.tmp.wav
-rw-r--r-- 1 loxberry loxberry  1743 Nov 27 23:37 Text2SIP_ztDv.job.tsp
```

**Comment by Woersty** [comment]
Kannst du mal prüfen, ob das bei dir auch hilft?
https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/6#issuecomment-263402609

**Comment by bla1bla1** [comment]
Hallo,

ich hab in den letzten beiden Tagen eine Menge geprüft und was soll ich sagen...
...wenn man der Firewall erlaubt, die eingehenden SIP & RTP Pakete durchzulassen, dann klappts auch mit dem Ton. In meinem Fall steht die FritzBox in einem anderen Subnet als die IP-Telefone.
Daher hat zwar interessanterweise die Telefonsignalisierung funktioniert, jedoch keine Tonübertragung.

Dennoch danke für deine Hilfe.
