### ISSUE TITLE
Option: Automatisches Auflegen nach MFV-Eingabe

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-Text2SIP#8]
Idee für neue Option: Automatisches Auflegen nach MFV-Eingabe

**Comment by Woersty** [comment]
Related to https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/6

**Comment by Woersty** [comment]
Nach Überlegung abgelehnt weil man einfach auflegen kann und fertig.

**Comment by Blaubart** [comment]
OK, ist richtig, dachte nur, ist etwas komfortabler ;-)

**Comment by Blaubart** [comment]
Und man hätte durch das Auflegen auch die Information, dass der Bestätigungscode ankam und interpretiert wurde

**Comment by Woersty** [comment]
>Und man hätte durch das Auflegen auch die Information, 
>dass der Bestätigungscode ankam und interpretiert wurde

Das wäre ein Grund, ja. Vielleicht noch eine Ansage "OK".
Ich denk nochmal drüber nach.
