### ISSUE TITLE
sipcmd: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by dwk-fks** [Woersty/LoxBerry-Plugin-Text2SIP#9]
Hallo,

nach dem Update meiner Fritzbox konnte ich meine Telnet Lösung nicht mehr nutzen um per Miniserver das Klingeln an der Tür auf den DECT Telefonen zu signalisieren und bin auf der Suche nach einer Alternative auf loxberry und das Plugin Text2SIP gestossen. Genau das was ich benötige...

Also habe ich mir die loxberry Version 0.2.2 installiert (virtuelle ESXi 6 Umgebung). Dann das Plugin installiert. Aber wenn ich von der Webseite versuche einen Test zu starten, bekomme ich folgendes Log.

Was habe ich bereits alles getan, bevor ich hier poste:
- versucht, loxberry version 0.2.1 zu nutzen. Aber ohne Erfolg. Bekam die Netzwerkkonfiguration nicht in den Griff.
- Hier bei github eine Anleitung gefunden, das Plugin neu zu machen. Getan. Gab ein anderes Log, aber auch andere Fehler.
- Das ganze System neu aufgesetzt. Nur das eine Plugin installiert. Nach der Installation alles neu gestartet, aber es verändert sich nichts.

Wer kann mir weiter helfen. Was mache ich falsch.

Und noch etwas... Wer das Log liest könnte sich über die IP der Fritzbox wundern. Ist aber richtig... 10.8.0.255/16. 
Und es ist egal, ob ich versuche die **9 oder eine andere Nummer anzurufen.

Liebe Grüße
Dieter W.

/opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd -T 1 -P sip -u 620 -c Oli1Nif8 -a "LoxBerry" -w 10.8.0.255 -x "c**9;w100;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_he5r.wav;w5000;h" 2>&1 |tee -a /opt/loxberry/log/plugins/text2sip/Text2SIP.log|while read DTMF_LINE; do echo $DTMF_LINE|grep -q "Exiting."; if [ $? -eq 0 ]; then wget -q -t 1 -T 10 -O /dev/null "http://Adminuser:Password@Miniserver:80/dev/sps/io/Text2SIP_1/0"; fi; DTMF_CODE=`echo $DTMF_LINE |grep "receive DTMF:"|cut -c16`; echo "DTMF: $DTMF_CODE"; wget -q -t 1 -T 10 -O /dev/null "http://Adminuser:Password@Miniserver:80/dev/sps/io/Text2SIP_1/$DTMF_CODE"; done 
Add job for guide 1 to queue as #2
################################ Start job from /opt/loxberry/data/plugins/text2sip/wav/Text2SIP_QgT6.job.tsp @ Sun Jan 15 21:54:11 2017 
Sun Jan 15 21:54:11 2017 ## Generating voice 
Sun Jan 15 21:54:11 2017 ## Converting voice 
Sun Jan 15 21:54:11 2017 ## Calling **9
/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_QgT6.job.tsp: line 7: /opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd: cannot execute binary file: Exec format error
2017-01-15 21:54:14 [LOG] Show logfile
Sun Jan 15 21:54:11 2017 ## Deleting files 
################################ End job from /opt/loxberry/data/plugins/text2sip/wav/Text2SIP_QgT6.job.tsp 
2017-01-15 21:54:20 [LOG] Show logfile

![2017-01-15_22h09_24](https://cloud.githubusercontent.com/assets/25139033/21966208/6cd40fe0-db6f-11e6-81e0-10f47998ccd9.png)

**Comment by Woersty** [comment]
Ich vermute für eine virtuelle Maschine muss das anders kompiliert werden.
Kannst du das > https://github.com/Woersty/LoxBerry-Plugin-Text2SIP/issues/6#issuecomment-263402609  < mal als Workaround probieren?

**Comment by dwk-fks** [comment]
Hallo Woersty,

habe ich probiert. Logfile sieht nun wie folgt aus. Geht aber leider nicht. 

```
OnIncomingConnection: token=L0bd031cf2
connection set up to sip:**9@10.8.0.255
```
Ist das so richtig? Ganz verstanden habe ich nicht, was da getan wird...
Danke für den Support und noch einen schönen Abend

Dieter W.


```
/opt/loxberry/webfrontend/cgi/plugins/text2sip/bin/sipcmd -T 60 -P sip -u 620 -c xxxxx -a "LoxBerry" -w 10.8.0.255 -x "c**9;w100;v/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_dDHy.wav;w5000;h" 2>&1 |tee -a /opt/loxberry/log/plugins/text2sip/Text2SIP.log|while read DTMF_LINE; do echo $DTMF_LINE|grep -q "Exiting."; if [ $? -eq 0 ]; then wget -q -t 1 -T 10 -O /dev/null "http://Adminuser:Password@Miniserver:80/dev/sps/io/Text2SIP_1/0"; fi; DTMF_CODE=`echo $DTMF_LINE |grep "receive DTMF:"|cut -c16`; echo "DTMF: $DTMF_CODE"; wget -q -t 1 -T 10 -O /dev/null "http://Adminuser:Password@Miniserver:80/dev/sps/io/Text2SIP_1/$DTMF_CODE"; done 
Add job for guide 1 to queue as #8
################################ Start job from /opt/loxberry/data/plugins/text2sip/wav/Text2SIP_k2XY.job.tsp @ Tue Jan 17 21:25:59 2017 
Tue Jan 17 21:25:59 2017 ## Generating voice 
Tue Jan 17 21:25:59 2017 ## Converting voice 
Tue Jan 17 21:25:59 2017 ## Calling **9
Starting LoxBerry Plugin Edition v0.2 by C.Woerstenfeld (C) 2016 git@loxberry.woerstenfeld.de 
Manager
Init
initialising SIP endpoint...
TestChanAudio
TestChanAudio
Listening for SIP signalling on 0.0.0.0:5060
SIP listener up
registered as sip:620@10.8.0.255
Created LocalEndPoint
Main
DIAL_TIMEOUT is 60
## Call ##
TestPhone::Main: calling "**9" using gateway "10.8.0.255" at Tue Jan 17 21:25:59 2017

Setting up a call to: sip:**9@10.8.0.255
LocalEndpoint::MakeConnection
LocalEndpointCreateConnection
LocalConnection
OnIncomingConnection: token=L0bd031cf2
connection set up to sip:**9@10.8.0.255
OnReleased: reason: EndedBySecurityDenial
## Wait: waiting for 100ms ##
OnReleased: reason: EndedBySecurityDenial
OnClearedCall
Wait: wait done
## Voice audiofile=/opt/loxberry/data/plugins/text2sip/wav/Text2SIP_dDHy.wav ##
PlaybackAudioFile
PlaybackAudioFile: state 3
## Wait: waiting for 5000ms ##
~LocalConnection
Wait: wait done
## Hangup ##
Hangup: at Tue Jan 17 21:26:04 2017

TestPhone::Main: shutting down
TestPhone::Main: exiting...
Exiting.
~Manager
2017-01-17 21:26:12 [LOG] Show logfile
```

**Comment by Woersty** [comment]
> connection set up to sip:**9@10.8.0.255
> OnReleased: reason: EndedBySecurityDenial

Ich würde sagen die SIP-User Zugangsdaten für 620 sind falsch.

**Comment by Woersty** [comment]
Keine Antwort mehr.

**Comment by cyberexpress** [comment]
Hallo Woersty,

ja - ist ein bisschen lange her der Eintrag, aber vielleicht hast du ja trotzdem eine Idee dazu. Ich habe nämlich genau das gleiche Problem wie er - "EndedBySerucityDenial" - habe deine Sipcmd aus dem Master zip genommen und bin nach Anleitung vorgegangen. Ich verwende eine 3CX Anlage zum testen - die Benutzerdaten stimmen (mit PhonerLite getestet). Habe auf Windows 10 das Ubuntu testeweise aktiviert um sipcmd mal außerhalb von Loxberry zu testen, jedoch ohne Erfolg. Ja - bei mir ist es auch eine VM aber ich habe soweit alles nachinstalliert und ansich keine Fehler mehr. Hast du eine Idee was man noch probieren könnte? Vielleicht vorher mal außerhalb von loxberry? lg. Christian

**Comment by Woersty** [comment]
Hallo, 
leider nein. Mein Wissensstand ist immer noch, dass das Tool nur auf dem Loxberry Prozessor läuft.
Du könntest höchstens noch ein Capture machen und dir im Wireshark ansehen,
was SIP-mäßig passiert.
Als root:  tcpdump -s0 -w dateiname.pcap 
Abbrechen mit Strg+c und dann Datei kopieren und am PC mit Wireshark öffnen. Ansichtsfilter: sip

Viele Grüße

**Comment by cyberexpress** [comment]
Servus,

ok - wäre es denn denkbar ein anderes Tool anstelle von sipcmd zu verwenden und die parameter entsprechend anzugleichen, damit es für die sipcmd alternative verwendbar ist?

lg.
